const sceneOptions=['通勤','视频会议','运动','长时间佩戴'];
const aspectOptions=['通话清晰','连接稳定','降噪','舒适度','续航'];
const state={scenes:new Set(['通勤','视频会议']),aspects:new Set(['通话清晰','连接稳定']),freeText:'每天地铁通勤约1小时，也会在办公室开视频会议，不希望频繁断连。',exclusions:new Set(['频繁断连']),compareProduct:null,demoState:'insufficient',error:''};
const screens={};
const navTop=(back='product',right='⋯')=>`<div class="topbar"><button class="back" aria-label="返回" onclick="go('${back}')">‹</button><div class="brand">听<i>荐</i></div><button class="ghost" aria-label="更多">${right}</button></div>`;
const chipButtons=(group,options)=>options.map(v=>`<button class="chip ${state[group].has(v)?'active':''}" aria-pressed="${state[group].has(v)}" onclick="toggle('${group}','${v}')">${v}</button>`).join('');
const sceneLabel=()=>[...state.scenes].join('、')||'未明确场景';
const needSummary=()=>`${sceneLabel()}；重点关注${[...state.aspects].join('、')||'未指定维度'}${state.exclusions.size?`；排除${[...state.exclusions].join('、')}`:''}`;

screens.product=()=>`${navTop('product')}<div class="hero"></div><section class="content"><div class="eyebrow">概念商品 A · DEMO TWS A</div><h1 class="title">无线耳机概念样本</h1><p class="sub">商品视觉与名称为虚构内容。评论片段仅用于演示证据结构，不代表对真实商品的推荐。</p><div class="rating">证据演示 <b>保留正反观点与缺失字段</b></div><div class="price">¥ -- <small>概念原型不提供价格</small></div><div class="ai-entry"><div><h3>AI帮我判断</h3><p>按你的场景重排评论证据</p></div><button class="round" aria-label="进入AI判断" onclick="go('needs')">›</button></div><button class="text-link" onclick="go('baseline')">进入普通评论基线任务 ›</button></section><nav class="bottom-nav"><b>商品</b><span>评价</span><span>参数</span><span>收藏</span></nav>`;

screens.needs=()=>`${navTop('product')}<section class="content"><div class="eyebrow">01 使用需求</div><h1 class="section-title">你准备怎么使用这副耳机</h1><p class="section-copy">场景会改变证据排序。提交后先确认AI的理解，再开始分析。</p><div class="label">主要场景</div><div class="chips">${chipButtons('scenes',sceneOptions)}</div><div class="label">最看重什么</div><div class="chips">${chipButtons('aspects',aspectOptions)}</div><div class="label">补充一句</div><textarea class="input" maxlength="300" oninput="state.freeText=this.value" aria-label="补充使用需求">${state.freeText}</textarea><p class="hint">最多300字。请不要填写姓名、电话或账号。</p>${state.error?`<p class="error-text">${state.error}</p>`:''}</section><button class="cta" onclick="prepareConfirmation()">检查AI理解</button>`;

screens.confirm=()=>`${navTop('needs')}<section class="content"><div class="eyebrow">02 需求确认</div><h1 class="section-title">AI这样理解你的需求</h1><p class="section-copy">推断可能出错。请先修改标签，再确认分析。</p><div class="confirm-list"><article class="confirm-card"><h3>使用场景</h3><div class="tag-row">${tagList('scenes')}</div></article><article class="confirm-card"><h3>关注维度</h3><div class="tag-row">${tagList('aspects')}</div></article><article class="confirm-card"><h3>排除条件</h3><div class="tag-row">${tagList('exclusions')}</div><p class="confirm-note">“频繁断连”来自自然语言推断，属于硬性条件，需要你确认。</p></article><article class="confirm-card"><h3>原始需求</h3><p class="sub">${escapeHtml(state.freeText)||'未填写补充说明'}</p></article></div><button class="text-link" onclick="go('needs')">返回修改原始需求</button></section><button class="cta" onclick="go('loading')">确认并分析</button>`;

screens.loading=()=>`${navTop('confirm')}<section class="loading"><div><div class="pulse"><b>AI</b></div><h2>正在整理证据</h2><p class="sub">只依据当前概念商品的检索片段生成结论</p><div class="steps"><div class="done">需求已确认：${sceneLabel()}</div><div class="done">已按商品与主题检索片段</div><div>正在校验正反观点与引用</div></div></div></section>`;

screens.report=()=>`${navTop('confirm')}<section class="report-head"><div class="tiny">概念报告 · DEMO TWS A · 需求版本 1</div><h1>总体判断：不确定</h1><div class="match"><strong>${sceneLabel()}</strong><span>关键需求证据不足</span></div><div class="disclaimer">适配判断表示证据方向；证据强度表示结论可靠程度。两者都不是购买成功概率。</div></section><div class="summary-card"><h3>一句话判断</h3><div class="bullet"><span class="ico good">✓</span><span>现有片段支持“价格适中”和“低频表现符合预期”。</span></div><div class="bullet"><span class="ico warn">!</span><span>没有足够的地铁降噪、会议麦克风和连接稳定性证据，暂时不能判断是否适合你的核心场景。</span></div></div><section class="metric"><article class="metric-row"><div class="metric-top"><b>通话清晰度</b><span class="badge low">证据不足</span></div><div class="evidence-counts"><span class="pos">支持片段 0</span><span class="neg">反对片段 0</span></div><p>当前样本没有直接描述会议麦克风或对方听感。</p></article><article class="metric-row"><div class="metric-top"><b>连接稳定性</b><span class="badge mid">证据较弱</span></div><div class="evidence-counts"><span class="pos">支持片段 1</span><span class="neg">反对片段 0</span></div><p>“兼容手机”不能等同于长期连接稳定，因此只作为弱证据。</p></article><article class="metric-row action" onclick="go('evidence')"><div class="metric-top"><b>音质观点</b><button class="link">查看证据 ›</button></div><div class="evidence-counts"><span class="pos">支持片段 1</span><span class="neg">反对片段 1</span></div><p>低频得到肯定，但乐器细节出现反对意见。片段数过少，标记为观点冲突示例。</p></article><article class="metric-row action" onclick="go('compareSelect')"><div class="metric-top"><b>与另一款概念商品比较</b><button class="link">选择商品 ›</button></div><p>比较会沿用同一版需求，不把无数据解释为表现差。</p></article><button class="text-link" onclick="go('states')">查看异常与降级状态 ›</button></section>`;

screens.evidence=()=>`${navTop('report')}<section class="content"><div class="eyebrow">音质观点 证据详情</div><h1 class="section-title">结论来自哪些片段</h1><p class="section-copy">英文原文是依据，中文内容仅为摘要。片段数不等于独立用户数。</p><div class="evidence-tabs"><button class="chip active">全部 2</button><button class="chip">支持 1</button><button class="chip">反对 1</button></div><article class="evidence"><div class="evidence-head"><span>支持片段 1</span><span>来源键 B009A6CZYE</span></div><blockquote>“Moderately priced, with decent bass, and iPhone compatible.”</blockquote><div class="translation">AI中文摘要：评论者认为价格适中、低频符合预期，并提到手机兼容性。</div><p class="source-note">评分：数据源未提供 · 验证购买：数据源未提供 · 有用票：数据源未提供</p></article><article class="evidence"><div class="evidence-head"><span>反对片段 1</span><span>来源键 B009A6CZYE</span></div><blockquote>“Guitars are often inaccurate… highlights the weakness of these Sony cans.”</blockquote><div class="translation">AI中文摘要：评论者认为吉他声音还原不准确，暴露了细节表现的弱点。</div><p class="source-note">评分：数据源未提供 · 验证购买：数据源未提供 · 有用票：数据源未提供</p></article><div class="missing">来源限制：公开片段对应的真实商品类型尚未完成TWS核验，因此只用于说明证据结构，不支持真实购买结论。</div></section>`;

screens.compareSelect=()=>`${navTop('report')}<section class="content"><div class="eyebrow">03 选择对比商品</div><h1 class="section-title">沿用同一需求比较</h1><p class="section-copy">当前需求：${needSummary()}。MVP最多比较两款同类概念商品。</p><button class="product-choice ${state.compareProduct==='B'?'selected':''}" onclick="selectProduct('B')"><span class="product-icon">B</span><span><h3>概念商品 B</h3><p>公开片段中包含长时间佩戴和眼镜使用描述；会议与通勤证据仍有限。</p></span></button><div class="missing">商品A和商品B的证据量不同。比较页会分别展示数量，并允许返回“无明确胜者”。</div></section><button class="cta" ${state.compareProduct?'':'disabled'} onclick="state.compareProduct?go('compare'):null" style="opacity:${state.compareProduct?1:.45}">生成比较结果</button>`;

screens.compare=()=>`${navTop('report')}<section class="content"><div class="eyebrow">同一需求下的比较</div><h1 class="section-title">两款商品都缺少关键场景证据</h1><p class="section-copy">比较需求：${needSummary()}。</p><div class="no-winner"><b>总体结果：无明确胜者。</b> 商品B在长时间佩戴方面有直接片段，但两款商品都无法回答会议麦克风和地铁降噪问题。</div><div class="compare-table"><div class="compare-row"><div>维度</div><div>概念商品A</div><div>概念商品B</div></div><div class="compare-row"><div>通话</div><div>无直接片段</div><div>无直接片段</div></div><div class="compare-row"><div>连接</div><div>弱证据 1段</div><div>证据有限</div></div><div class="compare-row"><div>舒适度</div><div>未明确回答</div><div class="winner">直接片段 1段</div></div><div class="compare-row"><div>音质</div><div>正反各1段</div><div>总体正面但量少</div></div></div><article class="evidence"><div class="evidence-head"><span>商品B代表性片段</span><span>来源键 B003VANOFY</span></div><blockquote>“Comfort wise I can wear these all day… even while wearing my glasses.”</blockquote><div class="translation">AI中文摘要：评论者表示戴眼镜时也能长时间佩戴。</div></article><p class="source-note">比较不提供购买按钮或强制推荐。真实上线前需要可许可、可追溯、已核验商品类型的数据源。</p></section>`;

screens.states=()=>`${navTop('report')}<section class="content"><div class="eyebrow">异常与降级状态</div><h1 class="section-title">系统不能可靠回答时怎么办</h1><p class="section-copy">选择一个状态，查看面向用户的解释和恢复动作。</p><div class="chips">${['insufficient','conflict','timeout','unavailable'].map(k=>`<button class="chip ${state.demoState===k?'active':''}" onclick="setDemoState('${k}')">${{insufficient:'证据不足',conflict:'观点冲突',timeout:'分析超时',unavailable:'商品不可分析'}[k]}</button>`).join('')}</div>${statePreview()}</section>`;

screens.baseline=()=>`${navTop('product')}<div class="timer"><span id="timerText">基线任务计时未开始</span><button onclick="toggleTimer()" id="timerButton">开始计时</button></div><section class="content"><div class="eyebrow">用户测试 基线材料</div><h1 class="section-title">直接浏览普通评论</h1><p class="section-copy">任务：判断这款概念耳机是否适合每天地铁通勤和办公室视频会议。</p>${[['★★★★★','Bass is decent and the price is fair.'],['★★★☆☆','It connects to my phone, but I did not test calls.'],['★★☆☆☆','Guitars often sound inaccurate and details are weak.'],['★★★★☆','Comfortable for casual listening, no comment on subway noise.']].map(([s,t])=>`<article class="baseline-review"><span class="stars">${s}</span><p>${t}</p></article>`).join('')}<div class="missing">这些片段刻意保持普通评论列表形式。完成判断后，记录用时和你的结论。</div></section>`;

function escapeHtml(text){return text.replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toggle(group,value){state[group].has(value)?state[group].delete(value):state[group].add(value);state.error='';render('needs')}
function tagList(group){const items=[...state[group]];return items.length?items.map(v=>`<span class="tag">${v}<button aria-label="删除${v}" onclick="removeTag('${group}','${v}')">×</button></span>`).join(''):'<span class="sub">未识别</span>'}
function removeTag(group,value){state[group].delete(value);render('confirm')}
function prepareConfirmation(){if(!state.scenes.size&&!state.freeText.trim()){state.error='请至少选择一个场景或填写一句需求。';render('needs');return}if(/断连|连接不稳|掉线/.test(state.freeText))state.exclusions.add('频繁断连');go('confirm')}
function selectProduct(key){state.compareProduct=key;render('compareSelect')}
function setDemoState(key){state.demoState=key;render('states')}
function statePreview(){const data={insufficient:['△','证据不足','当前没有足够的直接评论片段，无法判断该需求。','修改需求'],conflict:['⇄','观点冲突','支持和反对片段同时存在。系统保留分歧，不用证据强度掩盖冲突。','查看正反证据'],timeout:['…','分析超时','输入已保留。你可以重试，或先查看程序统计生成的模板结果。','重新分析'],unavailable:['○','暂不可分析','当前商品没有可映射的评论数据。普通评论入口仍然可用。','返回商品页']}[state.demoState];return `<article class="state-preview"><div class="symbol">${data[0]}</div><h2>${data[1]}</h2><p>${data[2]}</p><button class="retry" onclick="${state.demoState==='unavailable'?"go('product')":"go('needs')"}">${data[3]}</button></article>`}
let timerStart=null,timerHandle=null;
function toggleTimer(){const button=document.getElementById('timerButton');if(!timerStart){timerStart=Date.now();button.textContent='完成判断';timerHandle=setInterval(updateTimer,250)}else{clearInterval(timerHandle);updateTimer(true);button.disabled=true;button.textContent='已记录'}}
function updateTimer(done=false){const seconds=((Date.now()-timerStart)/1000).toFixed(1);document.getElementById('timerText').textContent=`${done?'基线任务完成':'正在计时'} ${seconds} 秒`}
function go(name){history.pushState({},'',`?screen=${name}`);render(name);if(name==='loading')setTimeout(()=>{if(new URLSearchParams(location.search).get('screen')==='loading')go('report')},1200)}
function render(name){document.getElementById('app').innerHTML=(screens[name]||screens.product)();document.getElementById('app').scrollTop=0}
window.onpopstate=()=>render(new URLSearchParams(location.search).get('screen')||'product');
render(new URLSearchParams(location.search).get('screen')||'product');
